using UnityEngine;
using UnityEditor;
using System.IO;
using System.Text;
using System.Collections.Generic;
using System.Linq;

public class SceneEnumGenerator : EditorWindow
{
    [MenuItem("Tools/Generate Scene Enum")]
    public static void ShowWindow()
    {
        GetWindow<SceneEnumGenerator>("Scene Enum Generator");
    }

    [MenuItem("Tools/Generate Scene Enum (Quick)")]
    public static void GenerateQuick()
    {
        GenerateSceneEnum();
    }

    private string outputPath = "Assets/Scripts/Generated";
    private string fileName = "SceneEnum.cs";
    private string enumName = "SceneEnum";
    private string namespaceName = "";
    private bool includeIndexes = true;
    private bool autoRefreshAfterGenerate = true;

    private void OnGUI()
    {
        GUILayout.Label("Scene Enum Generator", EditorStyles.boldLabel);
        GUILayout.Space(10);

        // 输出设置
        GUILayout.Label("Output Settings", EditorStyles.boldLabel);
        outputPath = EditorGUILayout.TextField("Output Path:", outputPath);
        fileName = EditorGUILayout.TextField("File Name:", fileName);
        enumName = EditorGUILayout.TextField("Enum Name:", enumName);
        namespaceName = EditorGUILayout.TextField("Namespace (Optional):", namespaceName);
        
        GUILayout.Space(5);
        includeIndexes = EditorGUILayout.Toggle("Include Scene Indexes", includeIndexes);
        autoRefreshAfterGenerate = EditorGUILayout.Toggle("Auto Refresh After Generate", autoRefreshAfterGenerate);

        GUILayout.Space(10);

        // 预览当前场景
        GUILayout.Label("Current Scenes in Build Settings:", EditorStyles.boldLabel);
        var scenes = GetScenesInBuildSettings();
        
        if (scenes.Count == 0)
        {
            EditorGUILayout.HelpBox("No scenes found in Build Settings!", MessageType.Warning);
        }
        else
        {
            EditorGUI.indentLevel++;
            foreach (var scene in scenes)
            {
                EditorGUILayout.LabelField($"{scene.index}: {scene.name}");
            }
            EditorGUI.indentLevel--;
        }

        GUILayout.Space(10);

        // 生成按钮
        GUI.enabled = scenes.Count > 0;
        if (GUILayout.Button("Generate Scene Enum", GUILayout.Height(30)))
        {
            GenerateSceneEnum();
        }
        GUI.enabled = true;

        GUILayout.Space(5);

        if (GUILayout.Button("Open Build Settings"))
        {
            EditorApplication.ExecuteMenuItem("File/Build Settings...");
        }
    }

    private static void GenerateSceneEnum()
    {
        var generator = new SceneEnumGenerator();
        generator.outputPath = "Assets/Scripts/Generated";
        generator.fileName = "SceneEnum.cs";
        generator.enumName = "SceneEnum";
        generator.namespaceName = "";
        generator.includeIndexes = true;
        generator.autoRefreshAfterGenerate = true;

        generator.DoGenerateEnum();
    }

    private void DoGenerateEnum()
    {
        var scenes = GetScenesInBuildSettings();
        
        if (scenes.Count == 0)
        {
            EditorUtility.DisplayDialog("Error", "No scenes found in Build Settings!", "OK");
            return;
        }

        // 确保输出目录存在
        if (!Directory.Exists(outputPath))
        {
            Directory.CreateDirectory(outputPath);
        }

        string fullPath = Path.Combine(outputPath, fileName);
        string enumContent = GenerateEnumContent(scenes);

        try
        {
            File.WriteAllText(fullPath, enumContent, Encoding.UTF8);
            
            if (autoRefreshAfterGenerate)
            {
                AssetDatabase.Refresh();
            }
            
            EditorUtility.DisplayDialog("Success", 
                $"Scene enum generated successfully!\nPath: {fullPath}\nScenes: {scenes.Count}", "OK");
                
            Debug.Log($"Scene enum generated: {fullPath}");
        }
        catch (System.Exception e)
        {
            EditorUtility.DisplayDialog("Error", $"Failed to generate enum:\n{e.Message}", "OK");
            Debug.LogError($"Failed to generate scene enum: {e}");
        }
    }

    private string GenerateEnumContent(List<SceneInfo> scenes)
    {
        var sb = new StringBuilder();
        
        // 文件头注释
        sb.AppendLine("// 此文件由SceneEnumGenerator自动生成，请勿手动修改");
        sb.AppendLine("// This file is auto-generated by SceneEnumGenerator, do not modify manually");
        sb.AppendLine($"// Generated at: {System.DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine();

        // using statements
        sb.AppendLine("using UnityEngine;");
        sb.AppendLine();

        // namespace开始
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
        }

        // 枚举定义
        string indent = string.IsNullOrEmpty(namespaceName) ? "" : "    ";
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// 场景枚举，对应Build Settings中的场景");
        sb.AppendLine($"{indent}/// Scene enum corresponding to scenes in Build Settings");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public enum {enumName}");
        sb.AppendLine($"{indent}{{");

        // 枚举值
        for (int i = 0; i < scenes.Count; i++)
        {
            var scene = scenes[i];
            string enumValue = SanitizeEnumName(scene.name);
            
            sb.AppendLine($"{indent}    /// <summary>");
            sb.AppendLine($"{indent}    /// {scene.name} (Build Index: {scene.index})");
            sb.AppendLine($"{indent}    /// </summary>");
            
            if (includeIndexes)
            {
                sb.AppendLine($"{indent}    {enumValue} = {scene.index}{(i < scenes.Count - 1 ? "," : "")}");
            }
            else
            {
                sb.AppendLine($"{indent}    {enumValue}{(i < scenes.Count - 1 ? "," : "")}");
            }
            
            if (i < scenes.Count - 1)
                sb.AppendLine();
        }

        sb.AppendLine($"{indent}}}");

        // 扩展方法类
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>");
        sb.AppendLine($"{indent}/// {enumName}的扩展方法");
        sb.AppendLine($"{indent}/// Extension methods for {enumName}");
        sb.AppendLine($"{indent}/// </summary>");
        sb.AppendLine($"{indent}public static class {enumName}Extensions");
        sb.AppendLine($"{indent}{{");
        
        // GetSceneName方法
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    /// 获取场景名称");
        sb.AppendLine($"{indent}    /// Get scene name");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public static string GetSceneName(this {enumName} scene)");
        sb.AppendLine($"{indent}    {{");
        sb.AppendLine($"{indent}        switch (scene)");
        sb.AppendLine($"{indent}        {{");
        
        foreach (var scene in scenes)
        {
            string enumValue = SanitizeEnumName(scene.name);
            sb.AppendLine($"{indent}            case {enumName}.{enumValue}: return \"{scene.name}\";");
        }
        
        sb.AppendLine($"{indent}            default: return scene.ToString();");
        sb.AppendLine($"{indent}        }}");
        sb.AppendLine($"{indent}    }}");
        
        // GetBuildIndex方法
        sb.AppendLine();
        sb.AppendLine($"{indent}    /// <summary>");
        sb.AppendLine($"{indent}    /// 获取场景构建索引");
        sb.AppendLine($"{indent}    /// Get scene build index");
        sb.AppendLine($"{indent}    /// </summary>");
        sb.AppendLine($"{indent}    public static int GetBuildIndex(this {enumName} scene)");
        sb.AppendLine($"{indent}    {{");
        
        if (includeIndexes)
        {
            sb.AppendLine($"{indent}        return (int)scene;");
        }
        else
        {
            sb.AppendLine($"{indent}        switch (scene)");
            sb.AppendLine($"{indent}        {{");
            
            foreach (var scene in scenes)
            {
                string enumValue = SanitizeEnumName(scene.name);
                sb.AppendLine($"{indent}            case {enumName}.{enumValue}: return {scene.index};");
            }
            
            sb.AppendLine($"{indent}            default: return -1;");
            sb.AppendLine($"{indent}        }}");
        }
        
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}}");

        // namespace结束
        if (!string.IsNullOrEmpty(namespaceName))
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    private List<SceneInfo> GetScenesInBuildSettings()
    {
        var scenes = new List<SceneInfo>();
        
        for (int i = 0; i < EditorBuildSettings.scenes.Length; i++)
        {
            var scene = EditorBuildSettings.scenes[i];
            if (scene.enabled)
            {
                string sceneName = Path.GetFileNameWithoutExtension(scene.path);
                scenes.Add(new SceneInfo { name = sceneName, index = i, path = scene.path });
            }
        }
        
        return scenes;
    }

    private string SanitizeEnumName(string sceneName)
    {
        // 移除无效字符并转换为有效的枚举名称
        string sanitized = sceneName;
        
        // 移除空格和特殊字符
        sanitized = System.Text.RegularExpressions.Regex.Replace(sanitized, @"[^a-zA-Z0-9_]", "_");
        
        // 确保不以数字开头
        if (char.IsDigit(sanitized[0]))
        {
            sanitized = "_" + sanitized;
        }
        
        // 转换为PascalCase
        if (sanitized.Contains("_"))
        {
            var parts = sanitized.Split('_');
            sanitized = string.Join("", parts.Select(p => 
                string.IsNullOrEmpty(p) ? "" : char.ToUpper(p[0]) + p.Substring(1).ToLower()));
        }
        else
        {
            sanitized = char.ToUpper(sanitized[0]) + sanitized.Substring(1);
        }
        
        return sanitized;
    }

    private struct SceneInfo
    {
        public string name;
        public int index;
        public string path;
    }
}
